### ISSUE TITLE
rename the project

### ISSUE THREAD

**Issue by torwag** [JFK20/ha-draw#11]
Hi,
it came to my attention, that the developers of tldraw kindly sugget to name projects not *tldraw*, to avoid that they might be mistaken for providing support. I therefore sugget to rename the project.
Taken similar projects and addons for HA, I feel that ``ha-draw`` might be a nice name, it reminds one on the tldraw component and add the typical ha for home assistant in front of it.

**Comment by JFK20** [comment]
its the done. The card itself also got renamed to ha-draw
