### ISSUE TITLE
Use of HA-templates

### ISSUE THREAD

**Issue by torwag** [JFK20/ha-draw#5]
Hi,
if I understood right, it is possible to execute home assistant templates from within a custom-card. The return value can then be used within the custom-card.

If we init the card we can access the template set in the config file as parameter ``template:``
``` 
       this._template = this.config.template || "";
```
Later on an entity change event, this can be used to execute the template within HA, which should make sure all safety measures of HA itself gets applied
```
const response = await hass.callApi("POST", "template", {
        template: this._template
``` 
Thus, one can execute arbitrary templates to map entity values to tldraw parameters.

**Comment by JFK20** [comment]
Templating is now Possible as it is Implemented via this [Class ](https://github.com/JFK20/ha-draw/blob/main/src/api/TemplateService.ts). And can be used when Template is set to one. For Example like this:
```yml
template: |
  {{ states('sensor.plug_pcsetup_leistung', with_unit=True) }}
```

**Comment by JFK20** [comment]
It's done, so if there are no objections, I would close this issue.

**Comment by torwag** [comment]
Sounds good to me
